# command to convert: gowall convert path/to/img.png -t <theme-name>
themes:
  - name: "kanagawa"
    colors:
      - "#1F1F28"
      - "#DCD7BA"
      - "#7E9CD8"
      - "#7FB4CA"
      - "#2D4F67"
      - "#DCD7BA"
      - "#727169"
      - "#DCD7BA"
      - "#363646"
      - "#938AA9"
      - "#2A2A37"
      - "#2A2A37"
      - "#2A2A37"
      - "#2A2A37"
      - "#54546D"
      - "#76946A"
      - "#C0A36E"
      - "#C34043"
      - "#76946A"
      - "#C0A36E"
      - "#C34043"
      - "#76946A"
      - "#C0A36E"
      - "#C34043"
      - "#7E9CD8"
      - "#957FB8"
      - "#938AA9"
      - "#76946A"
      - "#C0A36E"
      - "#C34043"
      - "#76946A"
      - "#C0A36E"
      - "#C34043"
      - "#76946A"
      - "#C0A36E"
      - "#C34043"
      - "#76946A"
      - "#C0A36E"
      - "#C34043"
      - "#76946A"
      - "#C0A36E"
      - "#C34043"
